-- AlterTable
ALTER TABLE "User" ADD COLUMN "email" TEXT;
ALTER TABLE "User" ADD COLUMN "fullName" TEXT;
ALTER TABLE "User" ADD COLUMN "phone" TEXT DEFAULT 'NA';
ALTER TABLE "User" ADD COLUMN "profileImg" TEXT;
